### ISSUE TITLE
Html content warning Invalid prop

### ISSUE THREAD

**Issue by andylacko** [alex-shamshurin/sweetalert2-react#19]
Hello, when I use this module, it constantly argues about prop being not boolean

**Warning: Failed prop type: Invalid prop `html` of type `string` supplied to `SweetAlert`, expected `boolean`.
    in SweetAlert (created by Campaign)
    in Campaign**

MY CODE:
```javascript
<SweetAlert
  show={saveConfirm}
  title={t('campaign.confirmCampaign')}
  html={renderToStaticMarkup(confirmModalHtml)}
  showCancelButton
  cancelButtonText={t('actions.cancel')}
  confirmButtonText={t('actions.confirm')}
  confirmButtonColor="#474F79"
  reverseButtons
  onConfirm={this.save.bind(this)}
  onCancel={this.valueByKey.bind(this, 'saveConfirm', false)}
  onEscapeKey={this.valueByKey.bind(this, 'saveConfirm', false)}
/>
```

but when I change it to html={true}, text={renderToStaticMarkup(confirmModalHtml)}, it doesn't work, maybe it is just forgotten **prop-type** check, or I am missing something? It works but with error warning

**Comment by LucidNinja** [comment]
I'm having the exact same issue. Any luck with this?

**Comment by LucidNinja** [comment]
I think that perhaps this issue has been fixed here on Github.  However, I'm using npm and it says that the most recent version is 0.7.2, which doesn't seem to be consistent with what's available here?

**Comment by nashequilibro** [comment]
Same issue. Any updates?

**Comment by sherriff93** [comment]
This is still an issue! Pulled down the code and it looks like its been changed to expect a string now (though the default value of html is still false). Is this just yet to be released?

**Comment by alex-shamshurin** [comment]
I have plans to update the package, but still hove no time and right now a bit out from the context.  Hallo, PRs are welcome. So it were no updates from the time I personally needed it.

**Comment by sherriff93** [comment]
Have made a PR here to change the default value of html to null: https://github.com/alex-shamshurin/sweetalert2-react/pull/22

The 'html: PropTypes.bool' was changed to 'html: PropTypes.string' in a previous PR, which would fix the error - just needs releasing.

**Comment by alex-shamshurin** [comment]
I have prepared new build, updated all deps, but it doesn't work, have problem with sweetalert2

**Comment by alex-shamshurin** [comment]
0.8.0 release with this fix and sweetalert2 update to latest version has been released!
